# global.toml is a special file for define global resources
# And look up from Resource.find(resource_name)


[mysqlconnection.mysqlconnection]
host="localhost"
port=3306
user="root"
passwd="root"
database="antares"
charset="utf8"


[redis.redis]
host="127.0.0.1"
port=6379


[logger.global]
filename="abc.log"
path="/Users/healer"


# Global variables!
[vars]
print_exception = 1
cinderella_device_id=2
hpge_path = "/Users/healer/Projects/privates/dauphine/examples"
